### ISSUE TITLE
大陆境内下载历史数据提示'远程主机强迫关闭了一个现有的连接。'

### ISSUE THREAD

**Issue by KennethAnn** [pyted/okx#17]
最近尝试下载历史行情数据，但是无论用okx的api还是直接request，都会提示如下错误，想请问应该如何解决？电脑为Windows系统，使用了VPN 
(Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

**Comment by langchou** [comment]
一样遇到这个问题，解决了吗？

**Comment by KennethAnn** [comment]
解决了，用蓝胖云vpn，https://clashv2ray.com/46451.html
